# Generated by Django 5.0.1 on 2025-06-08 12:31

from django.db import migrations, models


def migrate_categories_to_global(apps, schema_editor):
    """
    Convert restaurant-specific categories to global categories.
    This will create global categories with unique names and update menu items accordingly.
    """
    MenuCategory = apps.get_model('restaurants', 'MenuCategory')
    MenuItem = apps.get_model('restaurants', 'MenuItem')
    
    # Get all existing categories
    existing_categories = MenuCategory.objects.all()
    
    # Create a mapping of old category names to new global categories
    global_categories = {}
    
    for category in existing_categories:
        category_name = category.name
        
        # If we haven't seen this category name before, create a global one
        if category_name not in global_categories:
            # Check if a global category with this name already exists
            try:
                global_cat = MenuCategory.objects.get(name=category_name)
                global_categories[category_name] = global_cat
            except MenuCategory.DoesNotExist:
                # Create new global category
                global_cat = MenuCategory.objects.create(
                    name=category_name,
                    description=category.description,
                    order=category.order,
                    is_active=category.is_active,
                    created_at=category.created_at,
                    updated_at=category.updated_at
                )
                global_categories[category_name] = global_cat
        
        # Update all menu items that reference this old category
        MenuItem.objects.filter(category=category).update(
            category=global_categories[category_name]
        )
    
    # Delete old restaurant-specific categories (except the global ones we just created)
    for category in existing_categories:
        if category.id not in [gc.id for gc in global_categories.values()]:
            category.delete()


def reverse_migration(apps, schema_editor):
    """
    This reverse migration is not fully reversible since we lose the restaurant-category relationship.
    We'll just pass for now.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        # First, migrate the data
        migrations.RunPython(migrate_categories_to_global, reverse_migration),
        
        # Then alter the schema
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='restaurant',
        ),
    ]