# Generated by Django 5.0.1 on 2025-06-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_migrate_menu_categories_to_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display'),
        ),
    ]
