# Generated by Django 5.2.3 on 2025-06-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_menuitem_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('UZS', 'Uzbek Som (UZS)')], default='USD', max_length=3),
        ),
    ]
