# Generated by Django 5.2.3 on 2025-06-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_menuitem_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='currency',
        ),
    ]
