# Generated by Django 5.0.1 on 2025-06-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_convert_to_multi_role_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
