# Generated by Django 5.2.3 on 2025-06-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('BRL', 'Brazilian Real (R$)'), ('MXN', 'Mexican Peso ($)')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('BRL', 'Brazilian Real (R$)'), ('MXN', 'Mexican Peso ($)')], default='USD', max_length=3),
        ),
    ]
