# Generated by Django 5.0.1 on 2025-06-06 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('USER_REGISTERED', 'User Registered'), ('RESTAURANT_VIEWED', 'Restaurant Viewed'), ('MENU_ITEM_VIEWED', 'Menu Item Viewed'), ('SEARCH_PERFORMED', 'Search Performed'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('REVIEW_SUBMITTED', 'Review Submitted')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.menuitem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_a_event_t_6c35be_idx'), models.Index(fields=['user', 'created_at'], name='analytics_a_user_id_ecb128_idx'), models.Index(fields=['restaurant', 'created_at'], name='analytics_a_restaur_51e9ad_idx'), models.Index(fields=['order', 'created_at'], name='analytics_a_order_i_c6a55a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerInsights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('favorite_cuisine', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_order_time', models.CharField(blank=True, max_length=20, null=True)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('app_opens', models.IntegerField(default=0)),
                ('menu_views', models.IntegerField(default=0)),
                ('search_count', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'indexes': [models.Index(fields=['customer'], name='analytics_c_custome_fb7170_idx'), models.Index(fields=['restaurant'], name='analytics_c_restaur_2aca62_idx'), models.Index(fields=['total_spent'], name='analytics_c_total_s_17d8c0_idx')],
                'unique_together': {('customer', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('pending_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('average_preparation_time', models.IntegerField(default=0)),
                ('average_delivery_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['restaurant', 'date'], name='analytics_d_restaur_1f1b34_idx'), models.Index(fields=['date'], name='analytics_d_date_fdf0f8_idx')],
                'unique_together': {('restaurant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PopularMenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('popularity_rank', models.IntegerField(blank=True, null=True)),
                ('revenue_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-order_count'],
                'indexes': [models.Index(fields=['restaurant', 'date'], name='analytics_p_restaur_407ef2_idx'), models.Index(fields=['date', 'order_count'], name='analytics_p_date_4d6aef_idx')],
                'unique_together': {('menu_item', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RevenueMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dine_in_orders', models.IntegerField(default=0)),
                ('takeout_orders', models.IntegerField(default=0)),
                ('delivery_orders', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-date', '-hour'],
                'indexes': [models.Index(fields=['restaurant', 'date'], name='analytics_r_restaur_0a4a34_idx'), models.Index(fields=['date', 'hour'], name='analytics_r_date_0ed993_idx')],
                'unique_together': {('restaurant', 'date', 'hour')},
            },
        ),
    ]
