# Generated by Django 5.0.1 on 2025-05-29 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0003_alter_restaurant_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInsights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('favorite_cuisine', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_order_time', models.CharField(blank=True, max_length=20, null=True)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('app_opens', models.IntegerField(default=0)),
                ('menu_views', models.IntegerField(default=0)),
                ('search_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PopularMenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('popularity_rank', models.IntegerField(blank=True, null=True)),
                ('revenue_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-order_count'],
            },
        ),
        migrations.CreateModel(
            name='RevenueMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dine_in_orders', models.IntegerField(default=0)),
                ('takeout_orders', models.IntegerField(default=0)),
                ('delivery_orders', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', '-hour'],
            },
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_event_t_6c35be_idx',
            old_name='analytics_a_event_t_bb695f_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_user_id_ecb128_idx',
            old_name='analytics_a_user_id_c41f8d_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardstats',
            new_name='analytics_d_restaur_1f1b34_idx',
            old_name='analytics_d_restaur_58d1ac_idx',
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['restaurant', 'created_at'], name='analytics_a_restaur_51e9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['order', 'created_at'], name='analytics_a_order_i_c6a55a_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardstats',
            index=models.Index(fields=['date'], name='analytics_d_date_fdf0f8_idx'),
        ),
        migrations.AddField(
            model_name='customerinsights',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerinsights',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='popularmenuitems',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menuitem'),
        ),
        migrations.AddField(
            model_name='popularmenuitems',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='revenuemetrics',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AddIndex(
            model_name='customerinsights',
            index=models.Index(fields=['customer'], name='analytics_c_custome_fb7170_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinsights',
            index=models.Index(fields=['restaurant'], name='analytics_c_restaur_2aca62_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinsights',
            index=models.Index(fields=['total_spent'], name='analytics_c_total_s_17d8c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerinsights',
            unique_together={('customer', 'restaurant')},
        ),
        migrations.AddIndex(
            model_name='popularmenuitems',
            index=models.Index(fields=['restaurant', 'date'], name='analytics_p_restaur_407ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='popularmenuitems',
            index=models.Index(fields=['date', 'order_count'], name='analytics_p_date_4d6aef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='popularmenuitems',
            unique_together={('menu_item', 'date')},
        ),
        migrations.AddIndex(
            model_name='revenuemetrics',
            index=models.Index(fields=['restaurant', 'date'], name='analytics_r_restaur_0a4a34_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuemetrics',
            index=models.Index(fields=['date', 'hour'], name='analytics_r_date_0ed993_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revenuemetrics',
            unique_together={('restaurant', 'date', 'hour')},
        ),
    ]
