# Generated by Django 5.2.3 on 2025-06-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Food Delivery Platform', help_text='Name of the application', max_length=100)),
                ('default_currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('BRL', 'Brazilian Real (R$)'), ('MXN', 'Mexican Peso ($)'), ('UZS', 'Uzbek Som (som)')], default='USD', help_text='Default currency for the entire platform', max_length=3)),
                ('default_delivery_fee', models.DecimalField(decimal_places=2, default=2.99, help_text='Default delivery fee', max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum order amount', max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=15.0, help_text='Platform commission percentage', max_digits=5)),
                ('support_email', models.EmailField(default='support@fooddelivery.com', help_text='Support email address', max_length=254)),
                ('support_phone', models.CharField(blank=True, help_text='Support phone number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Settings',
                'verbose_name_plural': 'Application Settings',
            },
        ),
    ]
