# Generated by Django 5.2.3 on 2025-07-11 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('promotions', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpromotion',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='savedcart',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='savedcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'is_active'], name='cart_cart_user_id_5d777a_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key'], name='cart_cart_session_5e1af5_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['restaurant'], name='cart_cart_restaur_f211c3_idx'),
        ),
        migrations.AddIndex(
            model_name='cartabandonment',
            index=models.Index(fields=['user', 'abandoned_at'], name='cart_cartab_user_id_a54e50_idx'),
        ),
        migrations.AddIndex(
            model_name='cartabandonment',
            index=models.Index(fields=['restaurant', 'abandoned_at'], name='cart_cartab_restaur_e6ffb8_idx'),
        ),
        migrations.AddIndex(
            model_name='cartabandonment',
            index=models.Index(fields=['recovered'], name='cart_cartab_recover_7615a5_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='cart_cartit_cart_id_4fb076_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['menu_item'], name='cart_cartit_menu_it_35a430_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'menu_item')},
        ),
        migrations.AlterUniqueTogether(
            name='cartpromotion',
            unique_together={('cart', 'promotion')},
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['user', 'is_favorite'], name='cart_savedc_user_id_d2259e_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['restaurant'], name='cart_savedc_restaur_2d275b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedcart',
            unique_together={('user', 'name')},
        ),
    ]
