# Notifications app initial migration
# This would be generated by: python manage.py makemigrations notifications

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0003_alter_restaurant_id'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_PREPARING', 'Order Being Prepared'), ('ORDER_READY', 'Order Ready for Pickup'), ('ORDER_PICKED_UP', 'Order Picked Up'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_NEARBY', 'Driver Nearby'), ('PAYMENT_SUCCESSFUL', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('REVIEW_REQUEST', 'Review Request'), ('PROMOTION_AVAILABLE', 'Promotion Available'), ('RESTAURANT_OPENED', 'Restaurant Opened'), ('RESTAURANT_CLOSED', 'Restaurant Closed'), ('SYSTEM_MAINTENANCE', 'System Maintenance')], max_length=50, unique=True)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('send_push', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_push', models.BooleanField(default=False)),
                ('sent_email', models.BooleanField(default=False)),
                ('sent_sms', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('action_text', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('related_restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_updates_push', models.BooleanField(default=True)),
                ('order_updates_email', models.BooleanField(default=True)),
                ('order_updates_sms', models.BooleanField(default=False)),
                ('promotions_push', models.BooleanField(default=True)),
                ('promotions_email', models.BooleanField(default=False)),
                ('promotions_sms', models.BooleanField(default=False)),
                ('system_updates_push', models.BooleanField(default=True)),
                ('system_updates_email', models.BooleanField(default=False)),
                ('restaurant_orders_push', models.BooleanField(default=True)),
                ('restaurant_orders_email', models.BooleanField(default=True)),
                ('restaurant_reviews_push', models.BooleanField(default=True)),
                ('restaurant_reviews_email', models.BooleanField(default=True)),
                ('driver_assignments_push', models.BooleanField(default=True)),
                ('driver_assignments_sms', models.BooleanField(default=True)),
                ('do_not_disturb_start', models.TimeField(blank=True, null=True)),
                ('do_not_disturb_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='notification_recipie_c41f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['template', 'created_at'], name='notification_templat_bb695f_idx'),
        ),
    ]
